version: '3.8'

services:
  frontend:
    image: oven/bun:latest
    working_dir: /nuxt-app
    volumes:
      - ./nuxt-app:/nuxt-app
    command: sh -c "bun install && bun run dev"
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "4000:3000"
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:


networks:
  app-network:
